name: 'Discord'

on:
  push:
    branches: [master]

jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run Tests
      run: go test ./cmd/harmonize/...
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_GITHUB_TOKEN }}

  discord:
    needs: test

    name: 'Discord'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Harmonize Discord
      run: go run ./cmd/harmonize
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_ADMIN_BOT_TOKEN }}
